language: node_js
node_js:
  - 0.10

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - npm run test-single-run
  - npm run-script protractor
branches:
  only:
    - develop
